name: Unity - Activate

on:
  workflow_dispatch:

jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - name: Request manual activation file
        uses: game-ci/unity-request-manual-activation-file@v4
        with:
          unityVersion: 2022.3.21f1

      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: unity-activation-file
          path: unity-activation-file.alf
