name: Request Unity Activation File

on:
  workflow_dispatch:

jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - name: Request activation file
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2022.3.21f1
      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: Unity-activation-file
          path: unity.alf
