name: Run noVNC via Serveo

on:
  push:
    branches: [main]

jobs:
  novnc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip xvfb novnc websockify x11vnc openssh-client

    - name: Start Xvfb (virtual display)
      run: |
        Xvfb :1 -screen 0 1024x768x16 &
        export DISPLAY=:1
        echo "DISPLAY set to $DISPLAY"

    - name: Start x11vnc server
      run: |
        x11vnc -display :1 -forever -nopw -listen localhost -rfbport 5901 &
        echo "x11vnc started on localhost:5901"

    - name: Start noVNC
      run: |
        websockify --web /usr/share/novnc 6080 localhost:5901 &
        echo "noVNC started on port 6080"

    - name: Expose noVNC via Serveo
      run: |
        echo "Connecting to Serveo..."
        ssh -o StrictHostKeyChecking=no -R 80:localhost:6080 serveo.net
