name: Setup MySQL + phpMyAdmin

on:
  push:
    branches: [main]

jobs:
  setup-mysql:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        command: --sql-mode="NO_ENGINE_SUBSTITUTION"

    steps:
      - uses: actions/checkout@v3

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            mysql -h 127.0.0.1 -P 3306 -u root -proot -e "SELECT 1" && break
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Create nro_acc and import SQL
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -proot -e "CREATE DATABASE IF NOT EXISTS nro_acc CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
          mysql -h 127.0.0.1 -P 3306 -u root -proot --init-command="SET SESSION sql_mode='NO_ENGINE_SUBSTITUTION';" nro_acc < ./nro_acc.sql

      - name: Create nro_data and import SQL
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -proot -e "CREATE DATABASE IF NOT EXISTS nro_data CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
          mysql -h 127.0.0.1 -P 3306 -u root -proot --init-command="SET SESSION sql_mode='NO_ENGINE_SUBSTITUTION';" nro_data < ./nro_data.sql

      - name: Run phpMyAdmin
        run: |
          docker run --name phpmyadmin -d --rm -p 8080:80 \
            -e PMA_HOST=mysql \
            -e PMA_PORT=3306 \
            -e PMA_USER=root \
            -e PMA_PASSWORD=root \
            --network github_network_55f1559881ee41f981669c4d66d31e75 \
            phpmyadmin:latest
